# Site settings
title: Hairul Anuar Sulaiman
author: Hairul Anuar Bin Sulaiman
email: hairul.financial@gmail.com
description: >-
  Membantu individu dan keluarga di Malaysia membuat keputusan 
  kewangan yang lebih yakin berlandaskan prinsip Syariah.

# URL settings
url: "https://hairulanuarsulaiman.github.io"
baseurl: ""
phone: "+601127657730"
city: "Kota Tinggi"
state: "Johor"

# Build settings
markdown: kramdown
future: true

# Pagination settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 10
paginate_path: "/artikel/page:num/"

# Exclude these files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:title/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "posts"
    values:
      layout: post
      permalink: /artikel/:title/
